# Generated by Django 4.2.7 on 2023-12-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="crudst",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_name", models.CharField(max_length=100)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_notes", models.CharField(max_length=500)),
                ("contact_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
